name: Pre-Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true

jobs:
  create-release:
    name: Build and Create Tagged Pre release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Yarn cache
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "web/yarn.lock"

      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: web

      - name: Run build
        run: yarn build
        working-directory: web

        env:
          CI: false

      - name: Bundle files
        run: |
          mkdir -p ./temp/ox_inventory
          cp ./{server.lua,README.md,LICENSE,fxmanifest.lua,config.lua,client.lua} ./temp/ox_inventory
          cp -r ./{setup,modules,data} ./temp/ox_inventory
          cp -r ./web/build ./temp/ox_inventory/web
          cd ./temp && zip -r ox_inventory-${{ github.event.inputs.tag }}.zip ./ox_inventory

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        id: auto_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Experimental - ${{ github.event.inputs.tag }} (FOR TESTING PURPOSE)"
          prerelease: true
          automatic_release_tag: "${{ github.event.inputs.tag }}"
          files: ./temp/ox_inventory-${{ github.event.inputs.tag }}.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
